use serde::Serialize;

use crate::utils::AppResult;

/// Metadata for a release.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ReleaseMeta {
    pub version: String,
    pub date: String,
    pub changelog: Vec<String>,
    pub artifacts: Vec<String>,
    pub checksums: std::collections::HashMap<String, String>,
}

/// Manages release metadata and changelog generation.
pub struct ReleaseManager {
    version: String,
}

impl ReleaseManager {
    pub fn new(version: String) -> Self {
        Self { version }
    }

    /// Generate release metadata from the current build.
    pub fn build_release(&self) -> AppResult<ReleaseMeta> {
        let date = chrono::Utc::now().format("%Y-%m-%d").to_string();

        let artifacts = vec![
            format!("Nexus-Core-{}-windows-x86_64.msi", self.version),
            format!("Nexus-Core-{}-darwin-x86_64.dmg", self.version),
            format!("Nexus-Core-{}-linux-x86_64.AppImage", self.version),
        ];

        Ok(ReleaseMeta {
            version: self.version.clone(),
            date,
            changelog: Vec::new(),
            artifacts,
            checksums: std::collections::HashMap::new(),
        })
    }

    /// Generate a changelog from a list of entries.
    pub fn generate_changelog(entries: &[String]) -> Vec<String> {
        entries.to_vec()
    }

    /// Generate release notes in markdown format.
    pub fn generate_release_notes(version: &str, changelog: &[String]) -> String {
        let mut notes = format!("# Nexus Core v{version}\n\n");
        notes.push_str("## Changes\n\n");
        for entry in changelog {
            notes.push_str(&format!("- {entry}\n"));
        }
        notes.push_str("\n## Downloads\n\n");
        notes.push_str(&format!(
            "- [Windows](https://github.com/NexusCore/Nexus-Core/releases/download/v{version}/Nexus-Core-{version}-windows-x86_64.msi)\n"
        ));
        notes.push_str(&format!(
            "- [macOS](https://github.com/NexusCore/Nexus-Core/releases/download/v{version}/Nexus-Core-{version}-darwin-x86_64.dmg)\n"
        ));
        notes.push_str(&format!(
            "- [Linux](https://github.com/NexusCore/Nexus-Core/releases/download/v{version}/Nexus-Core-{version}-linux-x86_64.AppImage)\n"
        ));
        notes.push_str("\n---\n\n🤖 Generated by Nexus Core Release Manager\n");
        notes
    }

    /// Current version.
    pub fn version(&self) -> &str {
        &self.version
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_release_returns_meta() -> AppResult<()> {
        let rm = ReleaseManager::new("2.4.1".into());
        let meta = rm.build_release()?;
        assert_eq!(meta.version, "2.4.1");
        assert_eq!(meta.artifacts.len(), 3);
        assert!(!meta.date.is_empty());
        Ok(())
    }

    #[test]
    fn generates_changelog() {
        let entries = vec!["Fix DNS cache bug".into(), "Add GeoIP support".into()];
        let log = ReleaseManager::generate_changelog(&entries);
        assert_eq!(log.len(), 2);
    }

    #[test]
    fn release_notes_has_content() {
        let notes = ReleaseManager::generate_release_notes("1.0.0", &["Initial release".into()]);
        assert!(notes.contains("1.0.0"));
        assert!(notes.contains("Initial release"));
    }
}
