pub mod core_downloader;
pub mod core_extractor;
pub mod core_registry;
pub mod core_state;
pub mod installer_manager;
pub mod integrity_checker;
pub mod mirror_manager;
pub mod release_provider;
pub mod rollback_manager;
pub mod update_manager;
pub mod version_manager;

pub use core_downloader::CoreDownloader;
pub use core_extractor::CoreExtractor;
pub use core_registry::{CoreRegistry, VersionManifest};
pub use core_state::{CoreState, CoreStateCell};
pub use installer_manager::InstallerManager;
pub use integrity_checker::IntegrityChecker;
pub use mirror_manager::MirrorManager;
pub use release_provider::{GithubReleaseProvider, MirrorReleaseProvider, ReleaseProvider};
pub use rollback_manager::RollbackManager;
pub use update_manager::UpdateManager;
pub use version_manager::VersionManager;
